apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mlops-bootstrap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/isaiah1701/prod-mlops-platform.git
    targetRevision: main
    path: serving/helm
    helm:
      releaseName: prod-mlops-bootstrap
      valueFiles:
        - values/bootstrap.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
