{{- if and (not .Values.bootstrap.enabled) .Values.externalSecret.enabled }}
{{- $secret := .Values.externalSecret }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ required "externalSecret.secretStoreName is required" $secret.secretStoreName }}
  labels:
    {{- include "airbnb.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ required "externalSecret.aws.region is required" $secret.aws.region | quote }}
  conditions:
    - namespaces:
        - {{ .Release.Namespace | quote }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "externalSecret.name is required" $secret.name }}
  labels:
    {{- include "airbnb.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ $secret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ $secret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ $secret.name }}
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    {{- range $property := required "externalSecret.properties must contain keys" $secret.properties }}
    - secretKey: {{ $property }}
      remoteRef:
        key: {{ $secret.aws.secretId | quote }}
        property: {{ $property }}
    {{- end }}
{{- end }}
